"""
Orchestration Runner for Campaign Builder.

This module provides the main entry point for running the campaign building
pipeline, coordinating file discovery, analysis, and campaign planning.

This module provides:
    - CampaignBuilderResult: Result dataclass for pipeline execution
    - GeneratedFile: Dataclass for generated output files
    - ParameterSource: Dataclass for parameter provenance tracking
    - run_campaign_builder: Main async function to run the pipeline
    - Artifact writers for README and manifest generation
"""

import asyncio
import hashlib
import json
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, TypeVar

from campaign_builder.schemas import (
    CampaignError,
    ErrorCode,
    ErrorSeverity,
    FileGuide,
    detect_file_type,
)
from campaign_builder.schemas.errors import ErrorHandler, get_recovery_suggestion


# Type alias for progress callback
# callback(stage: str, progress: float, message: str)
ProgressCallback = Callable[[str, float, str], None]

# Pipeline stages for progress reporting
STAGE_DISCOVERING = "discovering"
STAGE_ANALYZING = "analyzing"
STAGE_PLANNING = "planning"
STAGE_VALIDATING = "validating"
STAGE_FINALIZING = "finalizing"
STAGE_COMPLETE = "complete"

# Type variable for generic timeout wrapper
T = TypeVar("T")


@dataclass
class GeneratedFile:
    """A file generated by the campaign builder.

    Attributes:
        path: Path to the generated file
        file_type: Type of file (e.g., "lammps_input", "readme")
        description: Human-readable description
        sha256_hash: Hash of the generated content
        source_files: List of source file paths used to generate this file
    """

    path: Path
    file_type: str
    description: str
    sha256_hash: str
    source_files: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "path": str(self.path),
            "file_type": self.file_type,
            "description": self.description,
            "sha256_hash": self.sha256_hash,
            "source_files": self.source_files,
        }


@dataclass
class ParameterSource:
    """Tracks the provenance of a parameter value.

    Attributes:
        parameter_name: Name of the parameter
        value: The parameter value
        source_file: File where the parameter was found
        source_line: Line number in the source file (if applicable)
        confidence: Confidence level (high/medium/low)
        notes: Additional notes about the parameter
    """

    parameter_name: str
    value: Any
    source_file: str
    source_line: Optional[int] = None
    confidence: str = "high"
    notes: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        result = {
            "parameter_name": self.parameter_name,
            "value": self.value,
            "source_file": self.source_file,
            "confidence": self.confidence,
        }
        if self.source_line is not None:
            result["source_line"] = self.source_line
        if self.notes:
            result["notes"] = self.notes
        return result


@dataclass
class CampaignBuilderResult:
    """Complete result of a campaign builder pipeline execution.

    Attributes:
        success: Whether the pipeline completed successfully
        intent: User's intent/description for the campaign
        workspace: Path to the input workspace
        files_found: Number of files discovered
        files_analyzed: Number of files successfully analyzed
        file_guides: List of FileGuide objects from analysis
        analysis_errors: Errors encountered during analysis
        campaign_plan: Generated campaign plan text (if available)
        generated_files: List of generated output files
        parameter_manifest: Parameter values with provenance
        output_directory: Path to output directory
        validation_summary: Summary of validation results
        readme_path: Path to generated README file
        manifest_path: Path to generated manifest file
        total_duration_ms: Total execution time in milliseconds
        analysis_duration_ms: File analysis duration in milliseconds
        planning_duration_ms: Campaign planning duration in milliseconds
        errors: All errors encountered
        warnings: Warning messages
        assumptions: Assumptions made during planning
    """

    # Status
    success: bool

    # Input summary
    intent: str
    workspace: Path
    files_found: int
    files_analyzed: int

    # Analysis results
    file_guides: List[FileGuide]
    analysis_errors: List[CampaignError]

    # Campaign results
    campaign_plan: Optional[str]
    generated_files: List[GeneratedFile]
    parameter_manifest: Dict[str, ParameterSource]

    # Output artifacts
    output_directory: Path
    validation_summary: str
    readme_path: Optional[Path]
    manifest_path: Optional[Path]

    # Metadata
    total_duration_ms: int
    analysis_duration_ms: int
    planning_duration_ms: int

    # Issues
    errors: List[CampaignError]
    warnings: List[str]
    assumptions: List[str]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "success": self.success,
            "intent": self.intent,
            "workspace": str(self.workspace),
            "files_found": self.files_found,
            "files_analyzed": self.files_analyzed,
            "file_guides": [fg.to_dict() for fg in self.file_guides],
            "analysis_errors": [e.to_dict() for e in self.analysis_errors],
            "campaign_plan": self.campaign_plan,
            "generated_files": [gf.to_dict() for gf in self.generated_files],
            "parameter_manifest": {
                k: v.to_dict() for k, v in self.parameter_manifest.items()
            },
            "output_directory": str(self.output_directory),
            "validation_summary": self.validation_summary,
            "readme_path": str(self.readme_path) if self.readme_path else None,
            "manifest_path": str(self.manifest_path) if self.manifest_path else None,
            "total_duration_ms": self.total_duration_ms,
            "analysis_duration_ms": self.analysis_duration_ms,
            "planning_duration_ms": self.planning_duration_ms,
            "errors": [e.to_dict() for e in self.errors],
            "warnings": self.warnings,
            "assumptions": self.assumptions,
        }

    def is_partial_success(self) -> bool:
        """Check if this is a partial success (some files analyzed, some failed)."""
        return (
            self.success
            and len(self.analysis_errors) > 0
            and self.files_analyzed > 0
        )


async def with_timeout(
    coro: Any,
    timeout_seconds: float,
    operation_name: str,
) -> Any:
    """Execute a coroutine with a timeout.

    Args:
        coro: The coroutine to execute
        timeout_seconds: Maximum time to wait in seconds
        operation_name: Name of the operation for error messages

    Returns:
        The result of the coroutine

    Raises:
        asyncio.TimeoutError: If the operation times out
    """
    try:
        return await asyncio.wait_for(coro, timeout=timeout_seconds)
    except asyncio.TimeoutError:
        raise asyncio.TimeoutError(
            f"Operation '{operation_name}' timed out after {timeout_seconds}s"
        )


def compute_file_hash(file_path: Path) -> str:
    """Compute SHA256 hash of a file.

    Args:
        file_path: Path to the file

    Returns:
        Hex-encoded SHA256 hash string
    """
    sha256_hash = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256_hash.update(chunk)
    return sha256_hash.hexdigest()


def discover_files(
    workspace: Path,
    error_handler: ErrorHandler,
    extensions: Optional[List[str]] = None,
) -> List[Path]:
    """Discover files in a workspace directory.

    Args:
        workspace: Path to the workspace directory
        error_handler: ErrorHandler to collect errors
        extensions: Optional list of extensions to filter (e.g., [".data", ".in"])

    Returns:
        List of discovered file paths
    """
    if not workspace.exists():
        error_handler.add(
            CampaignError(
                code=ErrorCode.E101_FILE_NOT_FOUND,
                severity=ErrorSeverity.FATAL,
                message=f"Workspace directory not found: {workspace}",
                file_path=str(workspace),
            )
        )
        return []

    if not workspace.is_dir():
        error_handler.add(
            CampaignError(
                code=ErrorCode.E302_INVALID_VALUE,
                severity=ErrorSeverity.FATAL,
                message=f"Workspace path is not a directory: {workspace}",
                file_path=str(workspace),
            )
        )
        return []

    discovered = []
    try:
        for item in workspace.rglob("*"):
            if item.is_file():
                # Skip hidden files and common non-relevant files
                if item.name.startswith("."):
                    continue
                if item.name in ("__pycache__", ".git", ".DS_Store"):
                    continue

                # Filter by extension if specified
                if extensions:
                    if item.suffix.lower() not in extensions:
                        continue

                discovered.append(item)
    except PermissionError as e:
        error_handler.add(
            CampaignError(
                code=ErrorCode.E103_FILE_UNREADABLE,
                severity=ErrorSeverity.ERROR,
                message=f"Permission denied accessing workspace: {e}",
                file_path=str(workspace),
            )
        )

    return sorted(discovered)


async def analyze_file(
    file_path: Path,
    error_handler: ErrorHandler,
) -> Optional[FileGuide]:
    """Analyze a single file and return a FileGuide.

    This is a placeholder implementation. In a full system, this would
    invoke the FileAnalyzer agent.

    Args:
        file_path: Path to the file to analyze
        error_handler: ErrorHandler to collect errors

    Returns:
        FileGuide if successful, None otherwise
    """
    try:
        # Compute file hash
        file_hash = compute_file_hash(file_path)

        # Detect file type
        file_type = detect_file_type(file_path)

        # Get file size
        file_size = file_path.stat().st_size

        # Create a basic FileGuide
        # In a full implementation, this would call the FileAnalyzer agent
        return FileGuide(
            file_path=str(file_path.absolute()),
            file_name=file_path.name,
            file_type=file_type,
            file_size_bytes=file_size,
            sha256_hash=file_hash,
            purpose=f"File of type {file_type.value}",
            summary=f"Discovered {file_type.value} file in workspace",
            confidence="medium",
            analysis_iterations=1,
        )

    except PermissionError:
        error_handler.add(
            CampaignError.file_unreadable(str(file_path), "Permission denied")
        )
        return None
    except Exception as e:
        error_handler.add(
            CampaignError(
                code=ErrorCode.E202_AGENT_FAILED,
                severity=ErrorSeverity.ERROR,
                message=f"Failed to analyze file: {e}",
                file_path=str(file_path),
            )
        )
        return None


async def analyze_all_files(
    files: List[Path],
    error_handler: ErrorHandler,
    progress_callback: Optional[ProgressCallback] = None,
    max_concurrent: int = 5,
) -> List[FileGuide]:
    """Analyze multiple files in parallel.

    Args:
        files: List of file paths to analyze
        error_handler: ErrorHandler to collect errors
        progress_callback: Optional callback for progress updates
        max_concurrent: Maximum concurrent analysis operations

    Returns:
        List of FileGuide objects for successfully analyzed files
    """
    if not files:
        return []

    file_guides: List[FileGuide] = []
    semaphore = asyncio.Semaphore(max_concurrent)

    async def analyze_with_semaphore(
        file_path: Path,
        index: int,
    ) -> Optional[FileGuide]:
        async with semaphore:
            if progress_callback:
                progress = (index + 1) / len(files)
                progress_callback(
                    STAGE_ANALYZING,
                    progress,
                    f"Analyzing {file_path.name} ({index + 1}/{len(files)})",
                )
            return await analyze_file(file_path, error_handler)

    # Create tasks for all files
    tasks = [
        analyze_with_semaphore(file_path, i)
        for i, file_path in enumerate(files)
    ]

    # Run all tasks concurrently
    results = await asyncio.gather(*tasks, return_exceptions=True)

    # Collect successful results
    for i, result in enumerate(results):
        if isinstance(result, Exception):
            error_handler.add(
                CampaignError(
                    code=ErrorCode.E202_AGENT_FAILED,
                    severity=ErrorSeverity.ERROR,
                    message=f"Analysis failed: {result}",
                    file_path=str(files[i]),
                )
            )
        elif result is not None:
            file_guides.append(result)

    return file_guides


def write_campaign_readme(
    output_dir: Path,
    intent: str,
    result: "CampaignBuilderResult",
) -> Path:
    """Write a README.md file summarizing the campaign.

    Args:
        output_dir: Directory to write the README
        intent: User's intent/description
        result: The CampaignBuilderResult

    Returns:
        Path to the generated README file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    readme_path = output_dir / "README.md"

    lines = [
        "# Campaign Builder Output",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Intent",
        "",
        intent,
        "",
        "## Summary",
        "",
        f"- **Files found:** {result.files_found}",
        f"- **Files analyzed:** {result.files_analyzed}",
        f"- **Analysis duration:** {result.analysis_duration_ms}ms",
        f"- **Planning duration:** {result.planning_duration_ms}ms",
        f"- **Total duration:** {result.total_duration_ms}ms",
        "",
    ]

    # Add file guides section
    if result.file_guides:
        lines.extend([
            "## Analyzed Files",
            "",
        ])
        for fg in result.file_guides:
            lines.extend([
                f"### {fg.file_name}",
                "",
                f"- **Type:** {fg.file_type.value}",
                f"- **Purpose:** {fg.purpose}",
                f"- **Confidence:** {fg.confidence}",
                "",
            ])

    # Add campaign plan if available
    if result.campaign_plan:
        lines.extend([
            "## Campaign Plan",
            "",
            result.campaign_plan,
            "",
        ])

    # Add generated files section
    if result.generated_files:
        lines.extend([
            "## Generated Files",
            "",
        ])
        for gf in result.generated_files:
            lines.append(f"- **{gf.path.name}**: {gf.description}")
        lines.append("")

    # Add warnings section
    if result.warnings:
        lines.extend([
            "## Warnings",
            "",
        ])
        for warning in result.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    # Add assumptions section
    if result.assumptions:
        lines.extend([
            "## Assumptions",
            "",
        ])
        for assumption in result.assumptions:
            lines.append(f"- {assumption}")
        lines.append("")

    # Add errors section
    if result.errors:
        lines.extend([
            "## Errors",
            "",
        ])
        for error in result.errors:
            lines.append(f"- [{error.code.value}] {error.message}")
        lines.append("")

    readme_path.write_text("\n".join(lines))
    return readme_path


def write_parameter_manifest(
    output_dir: Path,
    result: "CampaignBuilderResult",
) -> Path:
    """Write a manifest.json file with parameter provenance.

    Args:
        output_dir: Directory to write the manifest
        result: The CampaignBuilderResult

    Returns:
        Path to the generated manifest file
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / "manifest.json"

    manifest = {
        "generated_at": datetime.now().isoformat(),
        "success": result.success,
        "workspace": str(result.workspace),
        "intent": result.intent,
        "files": {
            "found": result.files_found,
            "analyzed": result.files_analyzed,
        },
        "parameters": {
            k: v.to_dict() for k, v in result.parameter_manifest.items()
        },
        "generated_files": [gf.to_dict() for gf in result.generated_files],
        "file_guides": [fg.to_dict() for fg in result.file_guides],
        "timing": {
            "total_ms": result.total_duration_ms,
            "analysis_ms": result.analysis_duration_ms,
            "planning_ms": result.planning_duration_ms,
        },
        "issues": {
            "errors": [e.to_dict() for e in result.errors],
            "warnings": result.warnings,
            "assumptions": result.assumptions,
        },
    }

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    return manifest_path


def create_failed_result(
    error_handler: ErrorHandler,
    workspace: Path,
    intent: str,
    output_dir: Path,
    duration_ms: int,
) -> CampaignBuilderResult:
    """Create a CampaignBuilderResult for a failed pipeline execution.

    Args:
        error_handler: ErrorHandler with collected errors
        workspace: Path to the workspace
        intent: User's intent/description
        output_dir: Output directory path
        duration_ms: Total duration in milliseconds

    Returns:
        CampaignBuilderResult indicating failure
    """
    return CampaignBuilderResult(
        success=False,
        intent=intent,
        workspace=workspace,
        files_found=0,
        files_analyzed=0,
        file_guides=[],
        analysis_errors=error_handler.get_errors(),
        campaign_plan=None,
        generated_files=[],
        parameter_manifest={},
        output_directory=output_dir,
        validation_summary="Pipeline failed before validation",
        readme_path=None,
        manifest_path=None,
        total_duration_ms=duration_ms,
        analysis_duration_ms=0,
        planning_duration_ms=0,
        errors=error_handler.get_errors(),
        warnings=[e.message for e in error_handler.get_warnings()],
        assumptions=[],
    )


def create_partial_success_report(result: CampaignBuilderResult) -> str:
    """Create a report for partial success scenarios.

    Args:
        result: The CampaignBuilderResult

    Returns:
        Formatted report string
    """
    lines = [
        "Partial Success Report",
        "=" * 60,
        "",
        f"Files successfully analyzed: {result.files_analyzed}/{result.files_found}",
        "",
    ]

    if result.analysis_errors:
        lines.append("Files that failed analysis:")
        for error in result.analysis_errors:
            suggestion = get_recovery_suggestion(error)
            lines.append(f"  - {error.file_path or 'Unknown file'}")
            lines.append(f"    Error: {error.message}")
            lines.append(f"    Suggestion: {suggestion}")
        lines.append("")

    if result.warnings:
        lines.append("Warnings:")
        for warning in result.warnings:
            lines.append(f"  - {warning}")
        lines.append("")

    if result.assumptions:
        lines.append("Assumptions made:")
        for assumption in result.assumptions:
            lines.append(f"  - {assumption}")
        lines.append("")

    return "\n".join(lines)


async def run_campaign_builder(
    intent: str,
    workspace: Path,
    output_dir: Path,
    progress_callback: Optional[ProgressCallback] = None,
    timeout_seconds: float = 300.0,
    max_concurrent_analysis: int = 5,
) -> CampaignBuilderResult:
    """Run the campaign builder pipeline.

    This is the main entry point for campaign building. It coordinates:
    1. File discovery in the workspace
    2. Parallel file analysis
    3. Campaign planning (placeholder)
    4. Artifact generation (README, manifest)

    Args:
        intent: User's description of the desired campaign
        workspace: Path to the workspace containing input files
        output_dir: Path to the output directory
        progress_callback: Optional callback for progress updates
        timeout_seconds: Maximum time for the entire pipeline
        max_concurrent_analysis: Maximum concurrent file analysis operations

    Returns:
        CampaignBuilderResult with complete pipeline results
    """
    start_time = time.time()
    error_handler = ErrorHandler()

    # Helper to compute elapsed time in ms
    def elapsed_ms() -> int:
        return int((time.time() - start_time) * 1000)

    try:
        # Stage 1: Discover files
        if progress_callback:
            progress_callback(STAGE_DISCOVERING, 0.0, "Discovering files...")

        files = discover_files(workspace, error_handler)

        if not error_handler.can_continue():
            return create_failed_result(
                error_handler, workspace, intent, output_dir, elapsed_ms()
            )

        files_found = len(files)

        if files_found == 0:
            error_handler.add_warning("No files found in workspace")
            return CampaignBuilderResult(
                success=True,
                intent=intent,
                workspace=workspace,
                files_found=0,
                files_analyzed=0,
                file_guides=[],
                analysis_errors=[],
                campaign_plan=None,
                generated_files=[],
                parameter_manifest={},
                output_directory=output_dir,
                validation_summary="No files to process",
                readme_path=None,
                manifest_path=None,
                total_duration_ms=elapsed_ms(),
                analysis_duration_ms=0,
                planning_duration_ms=0,
                errors=[],
                warnings=["No files found in workspace"],
                assumptions=[],
            )

        if progress_callback:
            progress_callback(
                STAGE_DISCOVERING, 1.0, f"Found {files_found} files"
            )

        # Stage 2: Analyze files
        analysis_start = time.time()

        if progress_callback:
            progress_callback(STAGE_ANALYZING, 0.0, "Starting file analysis...")

        file_guides = await with_timeout(
            analyze_all_files(
                files,
                error_handler,
                progress_callback,
                max_concurrent_analysis,
            ),
            timeout_seconds,
            "file_analysis",
        )

        analysis_duration_ms = int((time.time() - analysis_start) * 1000)
        files_analyzed = len(file_guides)

        if progress_callback:
            progress_callback(
                STAGE_ANALYZING,
                1.0,
                f"Analyzed {files_analyzed}/{files_found} files",
            )

        # Stage 3: Campaign planning (placeholder)
        planning_start = time.time()

        if progress_callback:
            progress_callback(STAGE_PLANNING, 0.0, "Planning campaign...")

        # In a full implementation, this would call run_campaign_planner
        campaign_plan = None
        assumptions: List[str] = []

        if file_guides:
            campaign_plan = f"Campaign plan for: {intent}\n\nBased on {files_analyzed} analyzed files."
            assumptions.append("Using default planning parameters")

        planning_duration_ms = int((time.time() - planning_start) * 1000)

        if progress_callback:
            progress_callback(STAGE_PLANNING, 1.0, "Campaign planning complete")

        # Stage 4: Validation (placeholder)
        if progress_callback:
            progress_callback(STAGE_VALIDATING, 0.0, "Validating results...")

        validation_summary = "Validation complete"
        if not file_guides:
            validation_summary = "No files were successfully analyzed"
        elif len(file_guides) < files_found:
            validation_summary = (
                f"Partial success: {files_analyzed}/{files_found} files analyzed"
            )

        if progress_callback:
            progress_callback(STAGE_VALIDATING, 1.0, validation_summary)

        # Stage 5: Finalization - write artifacts
        if progress_callback:
            progress_callback(STAGE_FINALIZING, 0.0, "Writing output artifacts...")

        # Determine success status
        success = files_analyzed > 0 or files_found == 0

        # Create result object
        result = CampaignBuilderResult(
            success=success,
            intent=intent,
            workspace=workspace,
            files_found=files_found,
            files_analyzed=files_analyzed,
            file_guides=file_guides,
            analysis_errors=error_handler.get_errors(),
            campaign_plan=campaign_plan,
            generated_files=[],
            parameter_manifest={},
            output_directory=output_dir,
            validation_summary=validation_summary,
            readme_path=None,
            manifest_path=None,
            total_duration_ms=elapsed_ms(),
            analysis_duration_ms=analysis_duration_ms,
            planning_duration_ms=planning_duration_ms,
            errors=error_handler.get_errors(),
            warnings=[e.message for e in error_handler.get_warnings()],
            assumptions=assumptions,
        )

        # Write artifacts
        if success:
            result.readme_path = write_campaign_readme(output_dir, intent, result)
            result.manifest_path = write_parameter_manifest(output_dir, result)
            result.generated_files = [
                GeneratedFile(
                    path=result.readme_path,
                    file_type="readme",
                    description="Campaign summary and documentation",
                    sha256_hash=compute_file_hash(result.readme_path),
                ),
                GeneratedFile(
                    path=result.manifest_path,
                    file_type="manifest",
                    description="Parameter manifest with provenance",
                    sha256_hash=compute_file_hash(result.manifest_path),
                ),
            ]

        if progress_callback:
            progress_callback(STAGE_FINALIZING, 1.0, "Artifacts written")

        # Stage 6: Complete
        result.total_duration_ms = elapsed_ms()

        if progress_callback:
            progress_callback(
                STAGE_COMPLETE, 1.0, f"Complete in {result.total_duration_ms}ms"
            )

        return result

    except asyncio.TimeoutError as e:
        error_handler.add(
            CampaignError(
                code=ErrorCode.E201_AGENT_TIMEOUT,
                severity=ErrorSeverity.FATAL,
                message=str(e),
            )
        )
        return create_failed_result(
            error_handler, workspace, intent, output_dir, elapsed_ms()
        )
    except Exception as e:
        error_handler.add(
            CampaignError(
                code=ErrorCode.E202_AGENT_FAILED,
                severity=ErrorSeverity.FATAL,
                message=f"Pipeline failed: {e}",
            )
        )
        return create_failed_result(
            error_handler, workspace, intent, output_dir, elapsed_ms()
        )


__all__ = [
    # Dataclasses
    "CampaignBuilderResult",
    "GeneratedFile",
    "ParameterSource",
    # Main function
    "run_campaign_builder",
    # Artifact writers
    "write_campaign_readme",
    "write_parameter_manifest",
    # Helpers
    "create_failed_result",
    "create_partial_success_report",
    "with_timeout",
    "discover_files",
    "analyze_all_files",
    "compute_file_hash",
    # Progress callback type
    "ProgressCallback",
    # Stage constants
    "STAGE_DISCOVERING",
    "STAGE_ANALYZING",
    "STAGE_PLANNING",
    "STAGE_VALIDATING",
    "STAGE_FINALIZING",
    "STAGE_COMPLETE",
]
